### ISSUE TITLE
Cannot build uncrustify on MinGW-64

### ISSUE THREAD

**Issue by guy-maurel** [uncrustify/uncrustify#1750]
I try to produce the version 0.67.
```.txt
   $ mkdir buildwin-32
   $ cd buildwin-32
   $ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw32.cmake -DCMAKE_EXE_LINKER_FLAGS="-static -s" ..
   $ make
```
I get some errors:
```.txt
...
[ 38%] Building CXX object CMakeFiles/uncrustify.dir/src/indent.cpp.obj
In file included from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/x86intrin.h:29:0,
                 from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/c++/i686-w64-mingw32/bits/opt_random.h:33,
                 from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/c++/random:50,
                 from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/c++/bits/stl_algo.h:66,
                 from /usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/c++/algorithm:62,
                 from /home/guy/Software/uncrustify/src/indent.cpp:18:
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/mmintrin.h: In function '__m64 _mm_cvtsi32_si64(int)':
/usr/lib/gcc/i686-w64-mingw32/5.3-win32/include/mmintrin.h:64:54: error: can't convert between vector values of different size
   return (__m64) __builtin_ia32_vec_init_v2si (__i, 0);

```
Can anybody help?

**Comment by mihaipopescu** [comment]
google tells me.. huh, guess what? https://github.com/uncrustify/uncrustify/issues/1154

**Comment by guy-maurel** [comment]
I am using Linux Mint 18.1 with the compiler identification is GNU 5.3.1
Running the same sources under Linux Mint 17.3 with compiler identification is GNU 4.8.2
doesnot generate any errors.

**Comment by mihaipopescu** [comment]
But I think it should not be your machine on which we should build the release versions but the ones build by AppVeyor and Travis. The build artifacts can be even uploaded to github or even sourceforge. And therefore the release procedure should be as simple as you pushing a version tag to github.

**Comment by jibsen** [comment]
Current master builds with mingw-w64 32-bit GCC 7.2.0 on my Windows machine. I wonder if there is some issue with GCC 5.3.1?

The Travis CI cross compiler appears to be 4.8.2, so testing the 32-bit build there probably wouldn't help.

**Comment by guy-maurel** [comment]
The problem is comming from the line:
```.cpp
// eliminate GNU's attribute
#define __attribute__(x)
```
introduce by Ben on Jun  9  2006
If I comment out the line, I get lot of warnings:
```.txt
uncrustify/src/indent.cpp:225:44: warning: unknown conversion type character 'z' in format [-Wformat=]
            get_token_name(pc->type), column);
uncrustify/src/indent.cpp:225:44: warning: format '%s' expects argument of type 'char*', but argument 5 has type 'size_t {aka unsigned int}' [-Wformat=]
```
I could use the old version (identification is GNU 4.8.2) to build the win32 binary.
What is the best?

**Comment by jibsen** [comment]
Might have to guard that define so it doesn't get included with GCC on Windows?

The format specifiers are because mingw-w64 does not provide standard compliant printf by default (it relies on a Windows API). You can [define](https://sourceforge.net/p/mingw-w64/wiki2/gnu%20printf/) `__USE_MINGW_ANSI_STDIO` to 1 to get correct printf with mingw-w64 on Windows.
